# fly.toml app configuration file generated for propertytoolsbyrotabackend on 2025-05-10T10:35:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# Config for backend BFF

app = 'propertytoolsbyrotabackend'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.http]
    interval = "15s"
    timeout = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
    grace_period = "5s"
    restart_limit = 0