# fly.toml app configuration file generated for propertytoolsbyrotabackend on 2025-05-10T10:35:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# Config for backend BFF

app = 'propertytoolsbyrotabackend'
primary_region = 'jnb'

[deploy]
strategy = "bluegreen" 

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1